import type { Campaign } from '@/domain/campaign/campaign'
import type { CheckIn } from '@/domain/autoregulation/check-in'
import type { FinanceReading } from '@/domain/finance/reading'
import type { Item } from '@/domain/backlog/item'
import type { DailyProgressEntry } from '@/domain/backlog/daily-goal'
import type { Exercise } from '@/domain/exercises/exercise'
import type { Project } from '@/domain/projects/project'
import type { Upgrade } from '@/domain/upgrades/upgrade'
import type { MetricDefinition, MonthlySnapshot } from '@/domain/review/metric'
import type { Friend } from '@/domain/social/circle'
import type { Place } from '@/domain/atlas/place/Place'
import type { Trip } from '@/domain/atlas/trip/Trip'
import type { Daily } from '@/domain/dailies/daily'
import type { Vice } from '@/domain/vitals/charges'
import type { WeighIn } from '@/domain/vitals/weight'
import type { WorkoutLog } from '@/domain/logging/workout-log'

import type { Resume } from '@/domain/resume/resume'
import type { SyncedSettings } from '@/domain/settings/synced'

import { indexTombstones, shouldAccept, type Tombstone } from './tombstone'

/**
 * A batch of changes moving in one direction.
 *
 * Deliberately the same four collections the backup envelope carries, and
 * deliberately *not* the envelope itself — a backup is a complete
 * snapshot with a checksum over the whole of it, and a sync batch is a
 * partial one. Reusing the envelope would have meant a checksum that
 * could not be checked and a "complete" file that was not.
 *
 * Position is absent, as it is from the envelope. It is the one record
 * with no correct last-write-wins answer — two devices advancing a single
 * cursor cannot be reconciled by comparing timestamps — so it stays
 * device-local, which is what makes everything else here safely
 * mergeable.
 */
export interface SyncPayload {
  readonly exercises: readonly Exercise[]
  readonly workouts: readonly WorkoutLog[]
  readonly checkIns: readonly CheckIn[]
  readonly items: readonly Item[]
  readonly projects: readonly Project[]
  readonly upgrades: readonly Upgrade[]
  readonly friends: readonly Friend[]
  readonly metrics: readonly MetricDefinition[]
  readonly reviews: readonly MonthlySnapshot[]
  readonly places: readonly Place[]
  readonly trips: readonly Trip[]
  readonly dailies: readonly Daily[]
  readonly vices: readonly Vice[]
  readonly weighIns: readonly WeighIn[]
  readonly finance: readonly FinanceReading[]
  readonly campaigns: readonly Campaign[]
  /**
   * Ground you have walked, as geohash cells.
   *
   * A grow-only set rather than a collection of records — see
   * `unionCells`. It carries no stamps and no tombstones because neither
   * question arises: two copies are merged by union, and nothing can
   * un-walk ground.
   */
  readonly exploredCells: readonly string[]
  readonly tombstones: readonly Tombstone[]
  /**
   * The travelling half of the settings, when they have changed.
   *
   * One blob rather than a collection, because there is one of them. It
   * is here at all because the program is *derived* from settings — two
   * devices with different tiers derive different programs, so syncing
   * history without the priorities that produced it is the half that only
   * looks like it works.
   *
   * Absent when nothing changed, and absent from anything a build without
   * this sent.
   */
  readonly settings?: SyncedSettings
  /**
   * The resume, when it has changed. The other singleton.
   *
   * It shipped in none of these lists — not the payload, not `isEmpty`,
   * not the backup envelope — so it existed on exactly one device with
   * no copy anywhere, while sync reported success on every run. It is
   * also the single most expensive record here to reproduce: everything
   * else is generated by using the app, and this one was typed in off a
   * PDF.
   *
   * Whole-record last-write-wins on `updatedAt`, which is right for the
   * same reason a weigh-in is: two devices holding a resume hold two
   * opinions about **one** document, so the later one is a correction
   * rather than something to merge. There are no per-day entries to
   * union, unlike a habit's completions.
   */
  readonly resume?: Resume
}

export const EMPTY_PAYLOAD: SyncPayload = {
  exercises: [],
  workouts: [],
  checkIns: [],
  items: [],
  projects: [],
  upgrades: [],
  friends: [],
  metrics: [],
  reviews: [],
  places: [],
  trips: [],
  dailies: [],
  exploredCells: [],
  vices: [],
  weighIns: [],
  finance: [],
  campaigns: [],
  tombstones: [],
}

export function isEmpty(payload: SyncPayload): boolean {
  return (
    payload.exercises.length === 0 &&
    payload.workouts.length === 0 &&
    payload.checkIns.length === 0 &&
    payload.items.length === 0 &&
    payload.projects.length === 0 &&
    payload.upgrades.length === 0 &&
    payload.friends.length === 0 &&
    payload.metrics.length === 0 &&
    payload.reviews.length === 0 &&
    payload.places.length === 0 &&
    payload.trips.length === 0 &&
    payload.dailies.length === 0 &&
    payload.vices.length === 0 &&
    payload.weighIns.length === 0 &&
    payload.finance.length === 0 &&
    payload.campaigns.length === 0 &&
    payload.exploredCells.length === 0 &&
    payload.tombstones.length === 0 &&
    payload.settings === undefined &&
    payload.resume === undefined
  )
}

export function payloadSize(payload: SyncPayload): number {
  return (
    payload.exercises.length +
    payload.workouts.length +
    payload.checkIns.length +
    payload.items.length +
    payload.projects.length +
    payload.upgrades.length +
    payload.friends.length +
    payload.metrics.length +
    payload.reviews.length +
    payload.places.length +
    payload.trips.length +
    payload.dailies.length +
    payload.vices.length +
    payload.weighIns.length +
    payload.finance.length +
    payload.campaigns.length +
    // Counted as one, because that is what it is to a reader: the fog
    // moved, once, however many cells were in the batch.
    (payload.exploredCells.length === 0 ? 0 : 1) +
    payload.tombstones.length +
    // Counted as one record, because that is what a lifter reading "sent
    // 3" is being told: three things moved, one of which was their
    // priorities.
    (payload.settings === undefined ? 0 : 1) +
    (payload.resume === undefined ? 0 : 1)
  )
}

/**
 * Merges two copies of one item's progress log, by day.
 *
 * The only place in this file where a *record's contents* are reconciled
 * rather than the record as a whole, and it is here because the general
 * rule genuinely does not apply.
 *
 * Whole-record last-write-wins is justified for a workout by how workouts
 * are used: you log sets on the phone in the gym and read the results at
 * your desk, so two devices editing one session is not a real scenario.
 * That reasoning does not transfer to a backlog. Reading a chapter on the
 * phone on Monday and an episode on the laptop on Tuesday — before the two
 * have spoken — is ordinary, and under a record-level winner Monday
 * silently vanishes: the laptop's copy is newer, and its progress log
 * never contained Monday at all.
 *
 * A progress log is append-only per day, so a union is the correct merge
 * and needs no timestamps. Where both copies claim the same day, the
 * larger count wins: neither device can have lost progress it recorded, so
 * the higher number is the one that saw more. The case that remains
 * imprecise is both devices logging the *same day* while apart, where two
 * separate readings show up as one — which is strictly better than the
 * record-level rule, under which the whole day disappears.
 */
export function unionProgress(
  mine: readonly DailyProgressEntry[],
  theirs: readonly DailyProgressEntry[],
): readonly DailyProgressEntry[] {
  const byDate = new Map<string, number>()

  for (const entry of [...mine, ...theirs]) {
    byDate.set(entry.date, Math.max(byDate.get(entry.date) ?? 0, entry.amount))
  }

  return [...byDate]
    .map(([date, amount]) => ({ date, amount }))
    .sort((a, b) => a.date.localeCompare(b.date))
}

/**
 * Merges two devices' completions for one habit.
 *
 * The same problem the backlog's progress log has, in its simplest form.
 * Tick Tuesday on the phone and Wednesday on the desktop with neither
 * having heard from the other, and whole-record last-write-wins keeps one
 * day and silently drops the other — which on a habit tracker means a
 * broken streak that was never broken.
 *
 * A set of day keys unions cleanly and needs no reconciliation at all: a
 * day is either done or it is not, and nobody can un-do a day on one
 * device in a way the other should respect. That is also why there is no
 * amount here, unlike `unionProgress` — there is nothing to take a
 * maximum of.
 */
export function unionDone(mine: readonly string[], theirs: readonly string[]): readonly string[] {
  return [...new Set([...mine, ...theirs])].sort()
}

/**
 * Merges two devices' explored ground.
 *
 * The one thing in this payload that is neither a record nor a blob, and
 * the reason it needs its own treatment is what it is: a set of cells you
 * have physically stood in.
 *
 * Down the record path it would be a single blob under one stamp — walk on
 * the phone, sync from the desktop, and the phone's morning is erased,
 * because the desktop's copy is newer and does not contain it. That is not
 * a merge going wrong; it is a merge with no way to go right.
 *
 * A set of revealed cells is **grow-only**, so union is not a compromise
 * between two answers — it is the answer. No timestamps are needed and
 * none are stored, because there is no ordering question to settle. No
 * tombstone is possible either: you cannot un-walk ground, and a deletion
 * would be a claim nobody is in a position to make.
 *
 * It is therefore exempt from `acceptableFrom` entirely. Every other
 * collection is filtered through the tombstone index on the way in; this
 * one has nothing to filter against.
 */
export function unionCells(mine: readonly string[], theirs: readonly string[]): readonly string[] {
  // Sorted so two devices that walked the same ground in a different order
  // produce byte-identical records, and the exchange stops re-sending a
  // set that has not actually changed.
  return [...new Set([...mine, ...theirs])].sort()
}

/**
 * The part of an incoming batch that survives everything known to be
 * deleted — both what this device deleted and what the batch itself says
 * was deleted.
 *
 * Both halves are needed. Filtering only on local tombstones lets a
 * record the *other* device deleted live on here forever, because this
 * device never witnessed the deletion and has nothing to compare against.
 * Filtering only on the incoming ones undoes local deletions, which is
 * the bug this whole mechanism exists to prevent.
 */
export function acceptableFrom(
  incoming: SyncPayload,
  localTombstones: readonly Tombstone[],
  /**
   * The local copies of the items being received.
   *
   * Needed only so a progress log can be unioned *before* the record-level
   * winner is chosen — by the time a record has won, the loser's days are
   * already gone.
   */
  localItems: readonly Item[] = [],
  localDailies: readonly Daily[] = [],
  /**
   * The local pools, for the same reason as the dailies above: the
   * spends have to be unioned *before* a record-level winner is picked,
   * or the losing copy's charges are gone by the time the merge runs.
   */
  localVices: readonly Vice[] = [],
): SyncPayload {
  const index = indexTombstones([...localTombstones, ...incoming.tombstones])
  const localById = new Map(localItems.map((item) => [item.id, item]))

  return {
    exercises: incoming.exercises.filter((item) => shouldAccept(item, 'exercises', item.id, index)),
    workouts: incoming.workouts.filter((item) => shouldAccept(item, 'workouts', item.id, index)),
    checkIns: incoming.checkIns.filter((item) => shouldAccept(item, 'checkIns', item.id, index)),
    items: incoming.items
      .filter((item) => shouldAccept(item, 'items', item.id, index))
      .map((item) => {
        const local = localById.get(item.id)
        if (local === undefined) return item

        return { ...item, dailyProgress: unionProgress(local.dailyProgress, item.dailyProgress) }
      }),
    projects: incoming.projects.filter((item) => shouldAccept(item, 'projects', item.id, index)),
    upgrades: incoming.upgrades.filter((item) => shouldAccept(item, 'upgrades', item.id, index)),
    friends: incoming.friends.filter((item) => shouldAccept(item, 'friends', item.id, index)),
    // Metrics carry no tombstone: removing a hand-defined metric is rare,
    // local, and leaves months of readings behind that would be orphaned
    // by a deletion travelling. It is deactivated rather than deleted.
    metrics: incoming.metrics,
    reviews: incoming.reviews.filter((item) => shouldAccept(item, 'reviews', item.month, index)),
    places: incoming.places.filter((item) => shouldAccept(item, 'places', item.id, index)),
    trips: incoming.trips.filter((item) => shouldAccept(item, 'trips', item.id, index)),
    dailies: incoming.dailies
      .filter((item) => shouldAccept(item, 'dailies', item.id, index))
      .map((daily) => {
        const local = localDailies.find((one) => one.id === daily.id)
        if (local === undefined) return daily

        return { ...daily, done: unionDone(local.done, daily.done) }
      }),
    /*
     * The spends union, and the record-level winner decides everything
     * else about the pool — its name, its capacity, its cooldown.
     *
     * The same shape as a daily's completions and for a sharper reason:
     * `readCharges` counts *entries* in this list, so a merge that kept
     * only one device's copy would silently give back charges that were
     * genuinely spent. Two coffees on the phone and a beer on the laptop
     * is three spends, whichever device syncs first.
     */
    vices: incoming.vices
      .filter((item) => shouldAccept(item, 'vices', item.id, index))
      .map((vice) => {
        const local = localVices.find((one) => one.id === vice.id)
        if (local === undefined) return vice

        return { ...vice, spent: unionDone(local.spent, vice.spent) }
      }),
    /*
     * Whole-record last-write-wins, and correct rather than lazy. Both
     * are keyed by the day, so two devices holding a row for the same
     * day are two opinions about **one fact** — this morning's weight,
     * how today felt — and the later answer is the one to keep. There is
     * nothing to union: unlike a set of completions, a second reading is
     * a correction rather than an addition.
     */
    weighIns: incoming.weighIns.filter((item) => shouldAccept(item, 'weighIns', item.day, index)),
    finance: incoming.finance.filter((item) => shouldAccept(item, 'finance', item.month, index)),
    campaigns: incoming.campaigns.filter((item) => shouldAccept(item, 'campaigns', item.id, index)),
    // Exempt on purpose. There is no tombstone that could apply to ground
    // somebody walked, so there is nothing here to filter against.
    exploredCells: incoming.exploredCells,
    tombstones: incoming.tombstones,
    // Passed through untouched. Settings cannot be deleted, so there is
    // no tombstone that could apply to them.
    ...(incoming.settings === undefined ? {} : { settings: incoming.settings }),
    // The same. A resume is edited down to nothing, never deleted, so
    // there is no tombstone collection for it either.
    ...(incoming.resume === undefined ? {} : { resume: incoming.resume }),
  }
}

/**
 * Records changed strictly after a watermark.
 *
 * Compared against the *local* clock on both sides, which is safe only
 * because this selects what to send rather than what to keep: every
 * `updatedAt` involved was written by this device. Deciding what to
 * *receive* uses a cursor the target issues, for exactly the reason this
 * cannot — two devices' clocks disagree, and a phone running four minutes
 * fast would otherwise hide four minutes of the desktop's work.
 */
export function changedSince<T extends { readonly updatedAt?: string }>(
  records: readonly T[],
  watermark: string | undefined,
): readonly T[] {
  /*
   * No `updatedAt` means the record was never written by this app's save
   * path, and shipped content is not a device's to send.
   *
   * This used to return everything when there was no watermark, which
   * reads as the obviously right answer for a first sync and is not: the
   * exercise library is *derived*, so `all()` hands back the whole
   * built-in catalogue alongside a lifter's own entries. A first sync
   * therefore uploaded thirty-five exercises that ship with the app,
   * keyed by slugs that are identical on every install — so two devices
   * wrote to the same documents, each overwrote the other, and each then
   * skipped them on pull as its own writes. Both reported sending ninety
   * records and receiving nothing, from databases holding no sessions at
   * all.
   *
   * The stamp is the right test rather than a filter on `isBuiltIn`,
   * because it generalises: a retired built-in that a lifter archived was
   * written by `save`, carries a stamp, and *should* travel to their
   * other device.
   */
  return records.filter(
    (record) =>
      record.updatedAt !== undefined && (watermark === undefined || record.updatedAt > watermark),
  )
}

export function deletedSince(
  tombstones: readonly Tombstone[],
  watermark: string | undefined,
): readonly Tombstone[] {
  if (watermark === undefined) return tombstones

  return tombstones.filter((tombstone) => tombstone.deletedAt > watermark)
}
