import type { Exercise, LoadBasis } from './exercise'
import type { Equipment, MovementPattern, MuscleGroup } from './taxonomy'

/**
 * The built-in exercise library.
 *
 * Grown from LiftTracker's forty seeded exercises — every one of which is
 * still here — with the gaps filled that its hardcoded session generator
 * had quietly required a lifter to work around: no unilateral leg work
 * beyond a split squat, no core, no carries, and no way to express an
 * exercise loaded by bodyweight plus a belt.
 *
 * Two fields are new and carry weight. `pattern` lets an assistance slot
 * be specified as "a vertical pull" rather than as a named exercise, which
 * is how 5/3/1 states its assistance requirements. `secondaryMuscles`
 * lets volume accounting credit a close-grip bench toward the triceps
 * without counting it as a full triceps set.
 *
 * These are seeds, not scripture. A lifter can edit any of them and add
 * their own; `isBuiltIn` only means an entry cannot be deleted outright,
 * because a program might reference it. It can be archived.
 */

interface CatalogueEntry {
  readonly slug: string
  readonly name: string
  readonly primaryMuscle: MuscleGroup
  readonly secondaryMuscles?: readonly MuscleGroup[]
  readonly equipment: Equipment
  readonly pattern: MovementPattern
  readonly isCompound: boolean
  readonly isUnilateral?: boolean
  readonly isCompetition?: boolean
  readonly loadBasis?: LoadBasis
  readonly defaultRepRange?: { readonly low: number; readonly high: number }
  readonly defaultRestSeconds?: number
}

/* The four lifts a 5/3/1 program is built on. Referenced by slug so a
   recipe can name them without knowing a generated id. */
export const MAIN_LIFT_SLUGS = {
  squat: 'back-squat',
  bench: 'bench-press',
  deadlift: 'conventional-deadlift',
  press: 'overhead-press',
} as const

const ENTRIES: readonly CatalogueEntry[] = [
  /* ---- Competition and main lifts -------------------------------- */
  {
    slug: 'bench-press',
    name: 'Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'front-delts'],
    equipment: 'barbell',
    pattern: 'horizontal-push',
    isCompound: true,
    isCompetition: true,
    loadBasis: 'training-max',
    defaultRepRange: { low: 3, high: 8 },
    defaultRestSeconds: 180,
  },
  {
    slug: 'back-squat',
    name: 'Back Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings', 'core'],
    equipment: 'barbell',
    pattern: 'squat',
    isCompound: true,
    isCompetition: true,
    loadBasis: 'training-max',
    defaultRepRange: { low: 3, high: 8 },
    defaultRestSeconds: 210,
  },
  {
    slug: 'conventional-deadlift',
    name: 'Conventional Deadlift',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'upper-back', 'lats', 'core', 'forearms'],
    equipment: 'barbell',
    pattern: 'hinge',
    isCompound: true,
    isCompetition: true,
    loadBasis: 'training-max',
    defaultRepRange: { low: 1, high: 5 },
    defaultRestSeconds: 240,
  },
  {
    slug: 'overhead-press',
    name: 'Overhead Press',
    primaryMuscle: 'front-delts',
    secondaryMuscles: ['triceps', 'side-delts', 'core'],
    equipment: 'barbell',
    pattern: 'vertical-push',
    isCompound: true,
    isCompetition: true,
    loadBasis: 'training-max',
    defaultRepRange: { low: 3, high: 8 },
    defaultRestSeconds: 180,
  },
  {
    slug: 'low-bar-squat',
    name: 'Low Bar Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings', 'core'],
    equipment: 'barbell',
    pattern: 'squat',
    isCompound: true,
    loadBasis: 'training-max',
    defaultRepRange: { low: 3, high: 8 },
  },
  {
    slug: 'high-bar-squat',
    name: 'High Bar Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'core'],
    equipment: 'barbell',
    pattern: 'squat',
    isCompound: true,
    loadBasis: 'training-max',
    defaultRepRange: { low: 5, high: 10 },
  },
  {
    slug: 'sumo-deadlift',
    name: 'Sumo Deadlift',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['quads', 'hamstrings', 'upper-back'],
    equipment: 'barbell',
    pattern: 'hinge',
    isCompound: true,
    loadBasis: 'training-max',
    defaultRepRange: { low: 1, high: 5 },
  },

  /* ---- Chest ------------------------------------------------------ */
  {
    slug: 'incline-bench-press',
    name: 'Incline Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['front-delts', 'triceps'],
    equipment: 'barbell',
    pattern: 'horizontal-push',
    isCompound: true,
    defaultRepRange: { low: 6, high: 10 },
  },
  {
    slug: 'incline-db-press',
    name: 'Incline DB Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['front-delts', 'triceps'],
    equipment: 'dumbbell',
    pattern: 'horizontal-push',
    isCompound: true,
    defaultRepRange: { low: 8, high: 12 },
  },
  {
    slug: 'flat-db-press',
    name: 'Flat DB Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'front-delts'],
    equipment: 'dumbbell',
    pattern: 'horizontal-push',
    isCompound: true,
    defaultRepRange: { low: 8, high: 12 },
  },
  {
    slug: 'close-grip-bench',
    name: 'Close-Grip Bench Press',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['chest', 'front-delts'],
    equipment: 'barbell',
    pattern: 'horizontal-push',
    isCompound: true,
    defaultRepRange: { low: 6, high: 10 },
  },
  {
    slug: 'dips',
    name: 'Dips',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'front-delts'],
    equipment: 'bodyweight',
    pattern: 'horizontal-push',
    isCompound: true,
    loadBasis: 'bodyweight',
    defaultRepRange: { low: 8, high: 15 },
  },
  {
    slug: 'pec-deck',
    name: 'Pec Deck',
    primaryMuscle: 'chest',
    equipment: 'machine',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 12, high: 15 },
  },
  {
    slug: 'incline-fly',
    name: 'Incline Fly',
    primaryMuscle: 'chest',
    equipment: 'dumbbell',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 12, high: 15 },
  },
  {
    slug: 'cable-crossover',
    name: 'Cable Crossover',
    primaryMuscle: 'chest',
    equipment: 'cable',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 12, high: 20 },
  },
  {
    slug: 'machine-chest-press',
    name: 'Machine Chest Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps'],
    equipment: 'machine',
    pattern: 'horizontal-push',
    isCompound: true,
    defaultRepRange: { low: 8, high: 12 },
  },
  {
    slug: 'push-up',
    name: 'Push-Up',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'core'],
    equipment: 'bodyweight',
    pattern: 'horizontal-push',
    isCompound: true,
    loadBasis: 'bodyweight',
    defaultRepRange: { low: 10, high: 25 },
  },

  /* ---- Shoulders -------------------------------------------------- */
  {
    slug: 'db-shoulder-press',
    name: 'DB Shoulder Press',
    primaryMuscle: 'front-delts',
    secondaryMuscles: ['triceps', 'side-delts'],
    equipment: 'dumbbell',
    pattern: 'vertical-push',
    isCompound: true,
    defaultRepRange: { low: 8, high: 12 },
  },
  {
    slug: 'machine-shoulder-press',
    name: 'Machine Shoulder Press',
    primaryMuscle: 'front-delts',
    secondaryMuscles: ['triceps'],
    equipment: 'machine',
    pattern: 'vertical-push',
    isCompound: true,
    defaultRepRange: { low: 8, high: 12 },
  },
  {
    slug: 'db-lateral-raise',
    name: 'DB Lateral Raise',
    primaryMuscle: 'side-delts',
    equipment: 'dumbbell',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 12, high: 20 },
  },
  {
    slug: 'cable-lateral-raise',
    name: 'Cable Lateral Raise',
    primaryMuscle: 'side-delts',
    equipment: 'cable',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 12, high: 20 },
  },
  {
    slug: 'machine-lateral-raise',
    name: 'Machine Lateral Raise',
    primaryMuscle: 'side-delts',
    equipment: 'machine',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 12, high: 20 },
  },
  {
    slug: 'reverse-pec-deck',
    name: 'Reverse Pec Deck',
    primaryMuscle: 'rear-delts',
    secondaryMuscles: ['upper-back'],
    equipment: 'machine',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 12, high: 20 },
  },
  {
    slug: 'face-pull',
    name: 'Face Pull',
    primaryMuscle: 'rear-delts',
    secondaryMuscles: ['upper-back'],
    equipment: 'cable',
    pattern: 'horizontal-pull',
    isCompound: false,
    defaultRepRange: { low: 15, high: 20 },
  },
  {
    slug: 'db-rear-delt-fly',
    name: 'DB Rear Delt Fly',
    primaryMuscle: 'rear-delts',
    equipment: 'dumbbell',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 12, high: 20 },
  },

  /* ---- Triceps ---------------------------------------------------- */
  {
    slug: 'rope-pushdown',
    name: 'Rope Pushdown',
    primaryMuscle: 'triceps',
    equipment: 'cable',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 12, high: 15 },
  },
  {
    slug: 'machine-tricep-extension',
    name: 'Machine Tricep Extension',
    primaryMuscle: 'triceps',
    equipment: 'machine',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 12, high: 15 },
  },
  {
    slug: 'skullcrusher',
    name: 'Skullcrusher',
    primaryMuscle: 'triceps',
    equipment: 'ez-bar',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 10, high: 15 },
  },
  {
    slug: 'db-overhead-extension',
    name: 'DB Overhead Extension',
    primaryMuscle: 'triceps',
    equipment: 'dumbbell',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 12, high: 15 },
  },

  /* ---- Back ------------------------------------------------------- */
  {
    slug: 'chin-up',
    name: 'Chin-Ups',
    primaryMuscle: 'lats',
    secondaryMuscles: ['biceps', 'upper-back'],
    equipment: 'bodyweight',
    pattern: 'vertical-pull',
    isCompound: true,
    loadBasis: 'bodyweight',
    defaultRepRange: { low: 6, high: 12 },
  },
  {
    slug: 'pull-up',
    name: 'Pull-Ups',
    primaryMuscle: 'lats',
    secondaryMuscles: ['biceps', 'upper-back'],
    equipment: 'bodyweight',
    pattern: 'vertical-pull',
    isCompound: true,
    loadBasis: 'bodyweight',
    defaultRepRange: { low: 5, high: 12 },
  },
  {
    slug: 'neutral-grip-pulldown',
    name: 'Neutral Grip Pulldown',
    primaryMuscle: 'lats',
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    pattern: 'vertical-pull',
    isCompound: true,
    defaultRepRange: { low: 10, high: 15 },
  },
  {
    slug: 'lat-pulldown',
    name: 'Lat Pulldown',
    primaryMuscle: 'lats',
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    pattern: 'vertical-pull',
    isCompound: true,
    defaultRepRange: { low: 10, high: 15 },
  },
  {
    slug: 'db-row',
    name: 'DB Row',
    primaryMuscle: 'lats',
    secondaryMuscles: ['upper-back', 'biceps'],
    equipment: 'dumbbell',
    pattern: 'horizontal-pull',
    isCompound: true,
    isUnilateral: true,
    defaultRepRange: { low: 8, high: 12 },
  },
  {
    slug: 'barbell-row',
    name: 'Barbell Row',
    primaryMuscle: 'upper-back',
    secondaryMuscles: ['lats', 'biceps', 'rear-delts'],
    equipment: 'barbell',
    pattern: 'horizontal-pull',
    isCompound: true,
    defaultRepRange: { low: 6, high: 10 },
  },
  {
    slug: 'machine-row',
    name: 'Machine Row',
    primaryMuscle: 'upper-back',
    secondaryMuscles: ['lats', 'biceps'],
    equipment: 'machine',
    pattern: 'horizontal-pull',
    isCompound: true,
    defaultRepRange: { low: 10, high: 15 },
  },
  {
    slug: 'cable-row',
    name: 'Seated Cable Row',
    primaryMuscle: 'upper-back',
    secondaryMuscles: ['lats', 'biceps'],
    equipment: 'cable',
    pattern: 'horizontal-pull',
    isCompound: true,
    defaultRepRange: { low: 10, high: 15 },
  },
  {
    slug: 'db-shrug',
    name: 'DB Shrugs',
    primaryMuscle: 'upper-back',
    equipment: 'dumbbell',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 12, high: 20 },
  },
  {
    slug: 'barbell-shrug',
    name: 'Barbell Shrugs',
    primaryMuscle: 'upper-back',
    equipment: 'barbell',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 10, high: 15 },
  },

  /* ---- Biceps and forearms ---------------------------------------- */
  {
    slug: 'barbell-curl',
    name: 'Barbell Curl',
    primaryMuscle: 'biceps',
    equipment: 'barbell',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 8, high: 12 },
  },
  {
    slug: 'hammer-curl',
    name: 'Hammer Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 10, high: 15 },
  },
  {
    slug: 'preacher-curl',
    name: 'Preacher Curl',
    primaryMuscle: 'biceps',
    equipment: 'ez-bar',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 10, high: 15 },
  },
  {
    slug: 'cable-curl',
    name: 'Cable Curl',
    primaryMuscle: 'biceps',
    equipment: 'cable',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 12, high: 15 },
  },
  {
    slug: 'incline-db-curl',
    name: 'Incline DB Curl',
    primaryMuscle: 'biceps',
    equipment: 'dumbbell',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 10, high: 15 },
  },
  {
    slug: 'farmers-carry',
    name: "Farmer's Carry",
    primaryMuscle: 'forearms',
    secondaryMuscles: ['core', 'upper-back'],
    equipment: 'dumbbell',
    pattern: 'carry',
    isCompound: true,
    defaultRepRange: { low: 30, high: 60 },
  },

  /* ---- Quads ------------------------------------------------------ */
  {
    slug: 'hack-squat',
    name: 'Hack Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes'],
    equipment: 'machine',
    pattern: 'squat',
    isCompound: true,
    defaultRepRange: { low: 8, high: 15 },
  },
  {
    slug: 'leg-press',
    name: 'Leg Press',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes'],
    equipment: 'machine',
    pattern: 'squat',
    isCompound: true,
    defaultRepRange: { low: 10, high: 20 },
  },
  {
    slug: 'front-squat',
    name: 'Front Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['core', 'glutes'],
    equipment: 'barbell',
    pattern: 'squat',
    isCompound: true,
    defaultRepRange: { low: 5, high: 10 },
  },
  {
    slug: 'split-squat',
    name: 'Bulgarian Split Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes'],
    equipment: 'dumbbell',
    pattern: 'lunge',
    isCompound: true,
    isUnilateral: true,
    defaultRepRange: { low: 8, high: 15 },
  },
  {
    slug: 'walking-lunge',
    name: 'Walking Lunge',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'dumbbell',
    pattern: 'lunge',
    isCompound: true,
    isUnilateral: true,
    defaultRepRange: { low: 10, high: 20 },
  },
  {
    slug: 'leg-extension',
    name: 'Leg Extension',
    primaryMuscle: 'quads',
    equipment: 'machine',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 12, high: 20 },
  },
  {
    slug: 'single-leg-extension',
    name: 'Single Leg Extension',
    primaryMuscle: 'quads',
    equipment: 'machine',
    pattern: 'isolation',
    isCompound: false,
    isUnilateral: true,
    defaultRepRange: { low: 12, high: 20 },
  },

  /* ---- Hamstrings and glutes -------------------------------------- */
  {
    slug: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'upper-back'],
    equipment: 'barbell',
    pattern: 'hinge',
    isCompound: true,
    defaultRepRange: { low: 8, high: 12 },
  },
  {
    slug: 'db-rdl',
    name: 'DB RDL',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes'],
    equipment: 'dumbbell',
    pattern: 'hinge',
    isCompound: true,
    defaultRepRange: { low: 10, high: 15 },
  },
  {
    slug: 'lying-leg-curl',
    name: 'Lying Leg Curl',
    primaryMuscle: 'hamstrings',
    equipment: 'machine',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 10, high: 15 },
  },
  {
    slug: 'seated-leg-curl',
    name: 'Seated Leg Curl',
    primaryMuscle: 'hamstrings',
    equipment: 'machine',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 10, high: 15 },
  },
  {
    slug: 'back-raise',
    name: 'Back Raise',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: 'bodyweight',
    pattern: 'hinge',
    isCompound: true,
    loadBasis: 'bodyweight',
    defaultRepRange: { low: 12, high: 20 },
  },
  {
    slug: 'hip-thrust',
    name: 'Hip Thrust',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'barbell',
    pattern: 'hinge',
    isCompound: true,
    defaultRepRange: { low: 8, high: 15 },
  },
  {
    slug: 'cable-pull-through',
    name: 'Cable Pull-Through',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'cable',
    pattern: 'hinge',
    isCompound: false,
    defaultRepRange: { low: 12, high: 20 },
  },

  /* ---- Calves ----------------------------------------------------- */
  {
    slug: 'standing-calf-raise',
    name: 'Standing Calf Raise',
    primaryMuscle: 'calves',
    equipment: 'machine',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 10, high: 20 },
  },
  {
    slug: 'seated-calf-raise',
    name: 'Seated Calf Raise',
    primaryMuscle: 'calves',
    equipment: 'machine',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 12, high: 20 },
  },
  {
    slug: 'leg-press-calf-raise',
    name: 'Leg Press Calf Raise',
    primaryMuscle: 'calves',
    equipment: 'machine',
    pattern: 'isolation',
    isCompound: false,
    defaultRepRange: { low: 12, high: 20 },
  },

  /* ---- Core ------------------------------------------------------- */
  {
    slug: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    primaryMuscle: 'core',
    equipment: 'bodyweight',
    pattern: 'core',
    isCompound: false,
    loadBasis: 'bodyweight',
    defaultRepRange: { low: 10, high: 20 },
  },
  {
    slug: 'cable-crunch',
    name: 'Cable Crunch',
    primaryMuscle: 'core',
    equipment: 'cable',
    pattern: 'core',
    isCompound: false,
    defaultRepRange: { low: 12, high: 20 },
  },
  {
    slug: 'ab-wheel',
    name: 'Ab Wheel Rollout',
    primaryMuscle: 'core',
    equipment: 'other',
    pattern: 'core',
    isCompound: false,
    loadBasis: 'bodyweight',
    defaultRepRange: { low: 8, high: 15 },
  },
  {
    slug: 'plank',
    name: 'Plank',
    primaryMuscle: 'core',
    equipment: 'bodyweight',
    pattern: 'core',
    isCompound: false,
    loadBasis: 'bodyweight',
  },
]

/**
 * Materialises the catalogue as domain entities.
 *
 * Ids are the slugs. They are stable, readable in an export file, and
 * mean a program written on one device references the same exercise on
 * another — which a generated UUID would not.
 */
export function builtInExercises(): readonly Exercise[] {
  return ENTRIES.map((entry) => ({
    id: entry.slug as Exercise['id'],
    name: entry.name,
    primaryMuscle: entry.primaryMuscle,
    secondaryMuscles: entry.secondaryMuscles ?? [],
    equipment: entry.equipment,
    pattern: entry.pattern,
    isCompound: entry.isCompound,
    isUnilateral: entry.isUnilateral ?? false,
    isCompetition: entry.isCompetition ?? false,
    loadBasis: entry.loadBasis ?? 'absolute-only',
    ...(entry.defaultRepRange !== undefined ? { defaultRepRange: entry.defaultRepRange } : {}),
    ...(entry.defaultRestSeconds !== undefined
      ? { defaultRestSeconds: entry.defaultRestSeconds }
      : {}),
    isBuiltIn: true,
    isArchived: false,
  }))
}

export const BUILT_IN_EXERCISE_COUNT = ENTRIES.length
