import type { MuscleGroup } from '@/domain/exercises/taxonomy'
import { MUSCLE_GROUP_LABELS, MUSCLE_GROUPS } from '@/domain/exercises/taxonomy'
import type { LiftSessions, StrengthLift } from '@/domain/priority/tiers'
import {
  DEFAULT_LIFT_SESSIONS,
  STRENGTH_LIFT_LABELS,
  STRENGTH_LIFTS,
  strengthSessionsFor,
} from '@/domain/priority/tiers'
import type { MuscleVolumes, SetsPerSession, VolumeLevel } from '@/domain/volume/levels'
import {
  DEFAULT_MUSCLE_VOLUMES,
  DEFAULT_SETS_PER_SESSION,
  setsPerSessionFor,
  VOLUME_LEVEL_LABELS,
  weeklySetsFor,
} from '@/domain/volume/levels'

/**
 * Why each muscle is getting the volume it is getting.
 *
 * The editor shows the *number*, which is the easy half. The number on
 * its own is unfalsifiable: six sets for the biceps looks arbitrary until
 * you can see it is two sessions of three because that is what you asked
 * for. Without the derivation a lifter cannot tell a considered
 * allocation from a bug, and cannot tell which input to change to move
 * it.
 *
 * Pure and separate from the UI, so the explanation is generated by the
 * same functions that produce the target. A prose description maintained
 * by hand drifts from the maths on the first change, and this is the one
 * thing in the app a lifter has no way to check.
 */

export type Band = 'maintaining' | 'building' | 'specialising'

export interface MuscleAllocation {
  readonly muscle: MuscleGroup
  readonly label: string
  readonly sessionsPerWeek: number
  readonly level: VolumeLevel
  readonly setsPerSession: number
  readonly weeklySets: number
  readonly band: Band
  /** One sentence naming every input that produced the number. */
  readonly reason: string
}

export interface StrengthAllocation {
  readonly lift: StrengthLift
  readonly label: string
  readonly sessionsPerWeek: number
  readonly reason: string
}

export interface VolumePlan {
  readonly muscles: readonly MuscleAllocation[]
  readonly lifts: readonly StrengthAllocation[]
  /** How many muscles get dedicated work at all. Reported, never applied. */
  readonly trainedCount: number
  readonly totalWeeklySets: number
}

/**
 * The band, which is now a reading of the weekly total rather than a rank.
 *
 * There is no tier to rename any more, so this answers the only question
 * a colour on a bar can usefully answer: is this muscle being pushed,
 * kept going, or left to the compounds? Thresholds rather than a lookup,
 * because two settings multiply into the number and no single one of them
 * decides it — three sessions of two sets and two sessions of three are
 * the same six sets and should read the same way.
 */
function bandFor(weeklySets: number, sets: SetsPerSession): Band {
  if (weeklySets <= 0) return 'maintaining'
  return weeklySets >= sets.high * 2 ? 'specialising' : 'building'
}

function list(values: readonly string[]): string {
  if (values.length === 0) return 'nothing'
  if (values.length === 1) return values[0] ?? ''
  return `${values.slice(0, -1).join(', ')} and ${values[values.length - 1] ?? ''}`
}

function sentenceCase(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1)
}

/*
 * Muscles always trained together read better as one word.
 *
 * "Biceps, triceps, forearms and side delts" is accurate and unusable as
 * a title. Collapsing only when *all* of a group is present keeps it
 * honest — emphasising biceps alone still says biceps.
 */
const GROUPS: readonly { readonly members: readonly MuscleGroup[]; readonly label: string }[] = [
  { members: ['biceps', 'triceps', 'forearms'], label: 'arms' },
  { members: ['quads', 'hamstrings', 'glutes', 'calves'], label: 'legs' },
  { members: ['lats', 'upper-back'], label: 'back' },
]

function name(muscles: readonly MuscleGroup[]): string[] {
  const remaining = new Set(muscles)
  const named: string[] = []

  for (const group of GROUPS) {
    if (!group.members.every((muscle) => remaining.has(muscle))) continue
    for (const muscle of group.members) remaining.delete(muscle)
    named.push(group.label)
  }

  return [
    ...named,
    ...muscles
      .filter((muscle) => remaining.has(muscle))
      .map((muscle) => MUSCLE_GROUP_LABELS[muscle].toLowerCase()),
  ]
}

/**
 * A name and a description generated from the settings themselves.
 *
 * Written by hand these went stale the first time anything moved — the
 * block still called itself "arms and side delts" long after the arms
 * came down. A description that describes the wrong program is worse than
 * none.
 *
 * What counts as the focus is now "the muscles getting the most weekly
 * sets", where it used to be "the muscles in tier 1". That is a real
 * change in meaning and a better one: a lifter who trains their side
 * delts three times a week has emphasised them whether or not they ever
 * opened a tier list, and the old version could not see it.
 */
/**
 * How far above the rest a muscle has to sit before the block is named
 * after it — one slot's work, the smallest amount of "more" this model
 * can express. Kept in step with `minSetsPerSlot` in `rp-assemble`.
 */
const FOCUS_MARGIN = 3

export function describeBlock(
  volumes: MuscleVolumes,
  sets: SetsPerSession,
  liftSessions: LiftSessions,
): {
  readonly name: string
  readonly description: string
  readonly focus: { readonly muscles: string; readonly lifts?: string }
} {
  const weekly = (muscle: MuscleGroup): number => weeklySetsFor(volumes[muscle], sets, false)

  const trained = MUSCLE_GROUPS.filter((muscle) => weekly(muscle) > 0)
  const untrained = MUSCLE_GROUPS.filter((muscle) => weekly(muscle) <= 0)

  /*
   * The focus is what stands out, and nothing stands out when everything
   * is level. Naming all eight trained muscles is a list, not a name.
   *
   * **A margin, not a tie-break**, and this is the second correction to
   * the same sentence. It was "the muscles in tier 1", then "the muscles
   * getting the most weekly sets" — better, and still wrong by one set:
   * the moment the upper body was divided between the two upper days,
   * the arms and calves came out at six weekly sets against everything
   * else's five, and the block renamed itself **"Triceps, biceps and
   * calves"**. Nobody had emphasised anything; three muscles were on two
   * days and five were on one.
   *
   * So the peak has to clear the floor by a whole slot's work before it
   * counts as a focus. That is the unit "more" comes in here — a muscle
   * is trained more by being given another session, and the smallest
   * session is `FOCUS_MARGIN` sets. One set of daylight is arithmetic;
   * three is a decision.
   */
  const peak = Math.max(0, ...trained.map(weekly))
  const floor = Math.min(...trained.map(weekly), peak)
  const emphasised = trained.filter((muscle) => weekly(muscle) === peak)
  const standsOut =
    emphasised.length > 0 && emphasised.length < trained.length && peak - floor >= FOCUS_MARGIN

  const mostSessions = Math.max(0, ...STRENGTH_LIFTS.map((lift) => liftSessions[lift]))
  const leadLifts = STRENGTH_LIFTS.filter((lift) => liftSessions[lift] === mostSessions)
  const liftStandsOut = mostSessions > 0 && leadLifts.length < STRENGTH_LIFTS.length

  const byLevel = (level: VolumeLevel): MuscleGroup[] =>
    trained.filter((muscle) => volumes[muscle].level === level)

  const sentences = [
    /*
     * No longer "RP volume": the landmarks that made that claim true are
     * gone, and citing a system this no longer implements would be the
     * kind of borrowed authority that is hardest to notice is wrong.
     */
    'Volume you set per muscle, with RTS autoregulated strength on the three lifts.',
    ...(['high', 'medium', 'low'] as const).map((level) => {
      const members = byLevel(level)
      return members.length > 0
        ? `${sentenceCase(list(name(members)))} at ${VOLUME_LEVEL_LABELS[level].toLowerCase()} volume.`
        : ''
    }),
    untrained.length > 0
      ? `${sentenceCase(list(name(untrained)))} left to the competition lifts.`
      : '',
    liftStandsOut
      ? `${sentenceCase(list(leadLifts.map((lift) => STRENGTH_LIFT_LABELS[lift].toLowerCase())))} ${leadLifts.length === 1 ? 'leads' : 'lead'} the strength work.`
      : '',
  ].filter((sentence) => sentence !== '')

  /*
   * The title carries both focuses, because a block has two. Where the
   * volume went says nothing about where the strength went, and a block
   * leading with the bench and one leading with the deadlift are
   * different blocks that would otherwise share a name.
   */
  const muscleFocus = standsOut ? sentenceCase(list(name(emphasised))) : 'General'
  const liftFocus = liftStandsOut
    ? `${sentenceCase(list(leadLifts.map((lift) => STRENGTH_LIFT_LABELS[lift].toLowerCase())))} strength`
    : undefined

  return {
    name: liftFocus === undefined ? muscleFocus : `${muscleFocus} · ${liftFocus}`,
    description: sentences.join(' '),
    /*
     * The two halves, unjoined. `name` is an identity and the interpunct
     * is doing the work of "and also"; a screen with room to lay the
     * block out properly should not have to split that string back apart.
     */
    focus: {
      muscles: muscleFocus,
      ...(liftFocus === undefined
        ? {}
        : {
            lifts: sentenceCase(
              list(leadLifts.map((lift) => STRENGTH_LIFT_LABELS[lift].toLowerCase())),
            ),
          }),
    },
  }
}

/**
 * What the week asks of each muscle, and where each number came from.
 *
 * **The three inputs are constants now rather than settings**, so they
 * default to what the assembler actually builds from — the volume
 * customisation was gutted, and a screen reading a copy the lifter could
 * no longer edit would be reporting on nothing. They stay as parameters
 * because the tests vary them, which is the whole reason this is a pure
 * function.
 */
export function explainVolume(
  volumes: MuscleVolumes = DEFAULT_MUSCLE_VOLUMES,
  sets: SetsPerSession = DEFAULT_SETS_PER_SESSION,
  liftSessions: LiftSessions = DEFAULT_LIFT_SESSIONS,
): VolumePlan {
  const muscles = MUSCLE_GROUPS.map((muscle): MuscleAllocation => {
    const volume = volumes[muscle]
    const perSession = setsPerSessionFor(volume.level, sets, false)
    const weeklySets = weeklySetsFor(volume, sets, false)

    return {
      muscle,
      label: MUSCLE_GROUP_LABELS[muscle],
      sessionsPerWeek: volume.sessionsPerWeek,
      level: volume.level,
      setsPerSession: perSession,
      weeklySets,
      band: bandFor(weeklySets, sets),
      /*
       * The whole derivation, because there is only one multiplication in
       * it. This used to name a landmark band the target was "pushed
       * toward the top of", which honestly described an interpolation and
       * would be a strange thing to say about a product of two settings.
       */
      reason:
        volume.sessionsPerWeek > 0
          ? `${String(volume.sessionsPerWeek)} session${volume.sessionsPerWeek === 1 ? '' : 's'} a week at ${VOLUME_LEVEL_LABELS[volume.level].toLowerCase()} volume — ${String(perSession)} sets each, ${String(weeklySets)} a week.`
          : 'Not trained directly. What the competition lifts pay it is what it gets.',
    }
  })

  const lifts = STRENGTH_LIFTS.map((lift): StrengthAllocation => {
    const sessions = strengthSessionsFor(liftSessions, lift)

    return {
      lift,
      label: STRENGTH_LIFT_LABELS[lift],
      sessionsPerWeek: sessions,
      /*
       * Only what differs between lifts. These sentences used to describe
       * a tier-dependent fatigue allowance, which stopped being true when
       * the allowance was flattened; the replacement then explained the
       * flat rule on every row, which trains the reader to skip all three
       * including the number that is not identical. What every session
       * shares belongs above the list, once.
       */
      reason:
        sessions > 0
          ? `${String(sessions)} session${sessions === 1 ? '' : 's'} a week.`
          : 'Not trained this block.',
    }
  })

  return {
    muscles,
    lifts,
    trainedCount: muscles.filter((entry) => entry.weeklySets > 0).length,
    totalWeeklySets: muscles.reduce((total, entry) => total + entry.weeklySets, 0),
  }
}
