import type { MuscleGroup } from '@/domain/exercises/taxonomy'
import { MUSCLE_GROUP_LABELS, MUSCLE_GROUPS } from '@/domain/exercises/taxonomy'
import type { LiftSessions } from '@/domain/priority/tiers'
import { STRENGTH_LIFT_LABELS, STRENGTH_LIFTS } from '@/domain/priority/tiers'
import type { MuscleVolumes, SetsPerSession, VolumeLevel } from '@/domain/volume/levels'
import { setsPerSessionFor, VOLUME_LEVEL_LABELS, weeklySetsFor } from '@/domain/volume/levels'

/**
 * Why each muscle is getting the volume it is getting.
 *
 * The editor shows the *number*, which is the easy half. The number on
 * its own is unfalsifiable: six sets for the biceps looks arbitrary until
 * you can see it is two sessions of three because that is what you asked
 * for. Without the derivation a lifter cannot tell a considered
 * allocation from a bug, and cannot tell which input to change to move
 * it.
 *
 * Pure and separate from the UI, so the explanation is generated by the
 * same functions that produce the target. A prose description maintained
 * by hand drifts from the maths on the first change, and this is the one
 * thing in the app a lifter has no way to check.
 */

function list(values: readonly string[]): string {
  if (values.length === 0) return 'nothing'
  if (values.length === 1) return values[0] ?? ''
  return `${values.slice(0, -1).join(', ')} and ${values[values.length - 1] ?? ''}`
}

function sentenceCase(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1)
}

/*
 * Muscles always trained together read better as one word.
 *
 * "Biceps, triceps, forearms and side delts" is accurate and unusable as
 * a title. Collapsing only when *all* of a group is present keeps it
 * honest — emphasising biceps alone still says biceps.
 */
const GROUPS: readonly { readonly members: readonly MuscleGroup[]; readonly label: string }[] = [
  { members: ['biceps', 'triceps', 'forearms'], label: 'arms' },
  { members: ['quads', 'hamstrings', 'glutes', 'calves'], label: 'legs' },
  { members: ['lats', 'upper-back'], label: 'back' },
]

function name(muscles: readonly MuscleGroup[]): string[] {
  const remaining = new Set(muscles)
  const named: string[] = []

  for (const group of GROUPS) {
    if (!group.members.every((muscle) => remaining.has(muscle))) continue
    for (const muscle of group.members) remaining.delete(muscle)
    named.push(group.label)
  }

  return [
    ...named,
    ...muscles
      .filter((muscle) => remaining.has(muscle))
      .map((muscle) => MUSCLE_GROUP_LABELS[muscle].toLowerCase()),
  ]
}

/**
 * A name and a description generated from the settings themselves.
 *
 * Written by hand these went stale the first time anything moved — the
 * block still called itself "arms and side delts" long after the arms
 * came down. A description that describes the wrong program is worse than
 * none.
 *
 * What counts as the focus is now "the muscles getting the most weekly
 * sets", where it used to be "the muscles in tier 1". That is a real
 * change in meaning and a better one: a lifter who trains their side
 * delts three times a week has emphasised them whether or not they ever
 * opened a tier list, and the old version could not see it.
 */
export function describeBlock(
  volumes: MuscleVolumes,
  sets: SetsPerSession,
  liftSessions: LiftSessions,
): {
  readonly name: string
  readonly description: string
  readonly focus: { readonly muscles: string; readonly lifts?: string }
} {
  const weekly = (muscle: MuscleGroup): number => weeklySetsFor(volumes[muscle], sets, false)

  const trained = MUSCLE_GROUPS.filter((muscle) => weekly(muscle) > 0)
  const untrained = MUSCLE_GROUPS.filter((muscle) => weekly(muscle) <= 0)

  /*
   * The focus is what stands out, and nothing stands out when everything
   * is level. Naming all the trained muscles is a list, not a name.
   *
   * **How hard a session is, not how many of them the week holds** — and
   * this is the third correction to one sentence, so the previous two are
   * worth stating. It was "the muscles in tier 1". Then it became "the
   * muscles getting the most weekly sets", on the reasoning that somebody
   * training their side delts three times a week has emphasised them
   * whether or not they ever opened a tier list. That was a real
   * improvement and it has stopped being true, because **frequency is no
   * longer something a person chooses.**
   *
   * The split decides it now: the upper body is divided between the two
   * upper days, so a muscle is on one day or two according to where its
   * accessory work is paired against the competition lifting. Four of
   * nine muscles landed at six weekly sets and five at three, and the
   * block called itself **"Triceps, biceps, calves and core"** — a true
   * statement about set counts and a useless name, because nobody had
   * emphasised anything.
   *
   * A *level* is still a decision, and it is the one that says "train
   * this harder": it is how long the single exercise for a muscle runs.
   * So the block is named after the muscles trained hardest per session,
   * and a week where every muscle shares a level — which the shipped week
   * does — is General, correctly.
   */
  const perSession = (muscle: MuscleGroup): number =>
    setsPerSessionFor(volumes[muscle].level, sets, false)

  const peak = Math.max(0, ...trained.map(perSession))
  const emphasised = trained.filter((muscle) => perSession(muscle) === peak)
  const standsOut = emphasised.length > 0 && emphasised.length < trained.length

  const mostSessions = Math.max(0, ...STRENGTH_LIFTS.map((lift) => liftSessions[lift]))
  const leadLifts = STRENGTH_LIFTS.filter((lift) => liftSessions[lift] === mostSessions)
  const liftStandsOut = mostSessions > 0 && leadLifts.length < STRENGTH_LIFTS.length

  const byLevel = (level: VolumeLevel): MuscleGroup[] =>
    trained.filter((muscle) => volumes[muscle].level === level)

  const sentences = [
    /*
     * No longer "RP volume": the landmarks that made that claim true are
     * gone, and citing a system this no longer implements would be the
     * kind of borrowed authority that is hardest to notice is wrong.
     */
    'Volume you set per muscle, with RTS autoregulated strength on the three lifts.',
    ...(['high', 'medium', 'low'] as const).map((level) => {
      const members = byLevel(level)
      return members.length > 0
        ? `${sentenceCase(list(name(members)))} at ${VOLUME_LEVEL_LABELS[level].toLowerCase()} volume.`
        : ''
    }),
    untrained.length > 0
      ? `${sentenceCase(list(name(untrained)))} left to the competition lifts.`
      : '',
    liftStandsOut
      ? `${sentenceCase(list(leadLifts.map((lift) => STRENGTH_LIFT_LABELS[lift].toLowerCase())))} ${leadLifts.length === 1 ? 'leads' : 'lead'} the strength work.`
      : '',
  ].filter((sentence) => sentence !== '')

  /*
   * The title carries both focuses, because a block has two. Where the
   * volume went says nothing about where the strength went, and a block
   * leading with the bench and one leading with the deadlift are
   * different blocks that would otherwise share a name.
   */
  const muscleFocus = standsOut ? sentenceCase(list(name(emphasised))) : 'General'
  const liftFocus = liftStandsOut
    ? `${sentenceCase(list(leadLifts.map((lift) => STRENGTH_LIFT_LABELS[lift].toLowerCase())))} strength`
    : undefined

  return {
    name: liftFocus === undefined ? muscleFocus : `${muscleFocus} · ${liftFocus}`,
    description: sentences.join(' '),
    /*
     * The two halves, unjoined. `name` is an identity and the interpunct
     * is doing the work of "and also"; a screen with room to lay the
     * block out properly should not have to split that string back apart.
     */
    focus: {
      muscles: muscleFocus,
      ...(liftFocus === undefined
        ? {}
        : {
            lifts: sentenceCase(
              list(leadLifts.map((lift) => STRENGTH_LIFT_LABELS[lift].toLowerCase())),
            ),
          }),
    },
  }
}
